services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDbSettings__ConnectionString=mongodb://root:mongopw@mongodb
    ports:
      - 7003:80
    depends_on:
      identity-service:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  identity-service:
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=Identity;User Id=postgres;Password=postgrespw
    ports:
      - 5000:80
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "dotnet", "--list-runtimes"]
      interval: 10s
      timeout: 5s
      retries: 5

  event-service:
    build:
      context: .
      dockerfile: src/EventService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=MeetEvents;User Id=postgres;Password=postgrespw
    ports:
      - 7001:80
    depends_on:
      identity-service:
        condition: service_healthy
      postgres:
        condition: service_healthy

  conversation-service:
    build:
      context: .
      dockerfile: src/ConversationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDbSettings__ConnectionString=mongodb://root:mongopw@mongodb
    ports:
      - 7004:80
    depends_on:
      identity-service:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  search-service:
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
    ports:
      - 7002:80
    depends_on:
      identity-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  gateway-service:
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
    depends_on:
      user-service:
        condition: service_started
      identity-service:
        condition: service_healthy
      event-service:
        condition: service_started
      conversation-service:
        condition: service_started
      search-service:
        condition: service_started

volumes:
  pgdata:
  mongodata:
