name: .NET Backend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
      - ".github/workflows/dotnet.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # MAUI workload installation removed

      # Use backend-only approach instead of full solution build
      - name: Restore backend only
        run: |
          dotnet restore src/Contracts/Contracts.csproj
          dotnet restore src/IdentityService/IdentityService.csproj
          dotnet restore src/EventService/EventService.csproj
          dotnet restore src/SearchService/SearchService.csproj
          dotnet restore src/UserService/UserService.csproj
          dotnet restore src/ConversationService/ConversationService.csproj
          dotnet restore src/GatewayService/GatewayService.csproj
          dotnet restore tests/SearchService.Tests/SearchService.Tests.csproj
          dotnet restore tests/EventService.Tests/EventService.Tests.csproj

      # Build backend services only (no MAUI)
      - name: Build backend only
        run: |
          dotnet build src/Contracts/Contracts.csproj --no-restore
          dotnet build src/IdentityService/IdentityService.csproj --no-restore
          dotnet build src/EventService/EventService.csproj --no-restore
          dotnet build src/SearchService/SearchService.csproj --no-restore
          dotnet build src/UserService/UserService.csproj --no-restore
          dotnet build src/ConversationService/ConversationService.csproj --no-restore
          dotnet build src/GatewayService/GatewayService.csproj --no-restore
          dotnet build tests/SearchService.Tests/SearchService.Tests.csproj --no-restore
          dotnet build tests/EventService.Tests/EventService.Tests.csproj --no-restore

      - name: Security scan
        uses: snyk/actions/dotnet@master
        continue-on-error: true # to make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Test Services
        run: |
          # Only test backend services, not client applications
          dotnet test tests/SearchService.Tests/SearchService.Tests.csproj --no-build --verbosity normal
          dotnet test tests/EventService.Tests/EventService.Tests.csproj --no-build --verbosity normal
